name: Check KVM Support

on: [push, pull_request]

jobs:
  check-kvm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cpu-checker

    - name: Check KVM support
      run: kvm-ok
