name: Check KVM Support

on: [push, pull_request]

jobs:
  check-kvm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        
        docker build -t android-emulator .
        
        docker run -it --privileged -d -p 5900:5900 --name androidContainer --privileged android-emulator  
        sleep 5  # Allow some time for the Docker container to start
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -R 80:localhost:5900 nokey@localhost.run
    - name: Check KVM support
      run: kvm-ok
