name: Check KVM Support

on: [push, pull_request]

jobs:
  check-kvm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        
        docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0
        sleep 5  # Allow some time for the Docker container to start
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -R 80:localhost:6080 nokey@localhost.run
    - name: Check KVM support
      run: kvm-ok
