name: Run Docker RTMP

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  run-docker-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Docker Command
        run: |
          docker run -d -p 1935:1935 --name nginx-rtmp tiangolo/nginx-rtmp
          sudo tar -xvzf ~/Downloads/https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
          ngrok config add-authtoken 2bQ5XWeLgb5gEBLa7dO4KQrob5N_2RN6V3LAx2UPspfuMPWYG
          ngrok http 1935
