name: Run Docker RTMP

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  run-docker-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Docker Command
        run: |
          wget -O ng.sh https://github.com/kmille36/Docker-Ubuntu-Desktop-NoMachine/raw/main/ngrok.sh > /dev/null 2>&1
          chmod +x ng.sh
          ./ng.sh
          docker run -p 6080:80 -v /dev/shm:/dev/shm -v ${PWD}/storage:/root elestio/docker-desktop-vnc
          ./ngrok config add-authtoken 2bQ5XWeLgb5gEBLa7dO4KQrob5N_2RN6V3LAx2UPspfuMPWYG
          ./ngrok http 6080



