name: Run Docker RTMP

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  run-docker-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Docker Command
        run: |
          docker run -d -p 6080:80 -v /dev/shm:/dev/shm -v ${PWD}/storage:/root elestio/docker-desktop-vnc
          sleep 5  # Allow some time for the Docker container to start
          ssh -o "StrictHostKeyChecking=yes" -R 80:localhost:6080 nokey@localhost.run
